// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// .env.local overrides .env (Vercel CLI pulls DB URLs here)
config({ path: ".env.local" });
config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["PORRA_POSTGRES_PRISMA_URL"]!,
    directUrl: process.env["PORRA_POSTGRES_URL_NON_POOLING"],
  },
});
